version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16
  working_directory: ~/project

dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm install -g yarn
    - yarn -v
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: |
          yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint-and-typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn tslint
  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          yarn test --coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-typecheck:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
